### ISSUE TITLE
Error when trying to wrap long strings

### ISSUE THREAD

**Issue by lwd27** [ttscoff/howzit_old#1]
If there is a string with no spaces that is longer than the wrap-length you get an error. In my case it was an URL over 80 characters. Setting -w 0 eliminates the error.

You can cause it also with shorter strings by setting -w to some number smaller than the string length.

**Comment by ttscoff** [comment]
Sorry I missed this ticket until now. I'll take a look at it.

**Comment by ttscoff** [comment]
Should be fixed in 1.1.1.
